compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

packageExtensions:
  '@chimera-monorepo/utils@*':
    dependencies:
      ethers: '5.7.2'
  '@chimera-monorepo/chainservice@*':
    dependencies:
      ethers: '5.7.2'
  '@mark/web3signer@*':
    dependencies:
      ethers: '5.7.2'

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'

yarnPath: .yarn/releases/yarn-3.3.1.cjs
