/*
** DON'T EDIT THIS FILE **
It's been generated by Zapatos, and is liable to be overwritten

Zapatos: https://jawj.github.io/zapatos/
Copyright (C) 2020 - 2023 George MacKerron
Released under the MIT licence: see LICENCE file
*/

declare module 'zapatos/schema' {

  import type * as db from 'zapatos/db';

  // got a type error on schemaVersionCanary below? update by running `npx zapatos`
  export interface schemaVersionCanary extends db.SchemaVersionCanary { version: 104 }


  /* === schema: public === */

  /* --- enums --- */
  /* (none) */

  /* --- tables --- */

  /**
   * **admin_actions**
   * - Table in database
   */
  export namespace admin_actions {
    export type Table = 'admin_actions';
    export interface Selectable {
      /**
      * **admin_actions.created_at**
      * - `timestamptz` in database
      * - Nullable, default: `now()`
      */
      created_at: Date | null;
      /**
      * **admin_actions.description**
      * - `text` in database
      * - Nullable, no default
      */
      description: string | null;
      /**
      * **admin_actions.id**
      * - `uuid` in database
      * - `NOT NULL`, default: `uuid_generate_v4()`
      */
      id: string;
      /**
      * **admin_actions.ondemand_rebalance_paused**
      *
      * Pause flag for on-demand rebalancing operations triggered by invoice processing
      * - `bool` in database
      * - Nullable, default: `false`
      */
      ondemand_rebalance_paused: boolean | null;
      /**
      * **admin_actions.purchase_paused**
      * - `bool` in database
      * - Nullable, default: `false`
      */
      purchase_paused: boolean | null;
      /**
      * **admin_actions.rebalance_paused**
      * - `bool` in database
      * - Nullable, default: `false`
      */
      rebalance_paused: boolean | null;
      /**
      * **admin_actions.updated_at**
      * - `timestamptz` in database
      * - Nullable, default: `now()`
      */
      updated_at: Date | null;
    }
    export interface JSONSelectable {
      /**
      * **admin_actions.created_at**
      * - `timestamptz` in database
      * - Nullable, default: `now()`
      */
      created_at: db.TimestampTzString | null;
      /**
      * **admin_actions.description**
      * - `text` in database
      * - Nullable, no default
      */
      description: string | null;
      /**
      * **admin_actions.id**
      * - `uuid` in database
      * - `NOT NULL`, default: `uuid_generate_v4()`
      */
      id: string;
      /**
      * **admin_actions.ondemand_rebalance_paused**
      *
      * Pause flag for on-demand rebalancing operations triggered by invoice processing
      * - `bool` in database
      * - Nullable, default: `false`
      */
      ondemand_rebalance_paused: boolean | null;
      /**
      * **admin_actions.purchase_paused**
      * - `bool` in database
      * - Nullable, default: `false`
      */
      purchase_paused: boolean | null;
      /**
      * **admin_actions.rebalance_paused**
      * - `bool` in database
      * - Nullable, default: `false`
      */
      rebalance_paused: boolean | null;
      /**
      * **admin_actions.updated_at**
      * - `timestamptz` in database
      * - Nullable, default: `now()`
      */
      updated_at: db.TimestampTzString | null;
    }
    export interface Whereable {
      /**
      * **admin_actions.created_at**
      * - `timestamptz` in database
      * - Nullable, default: `now()`
      */
      created_at?: (db.TimestampTzString | Date) | db.Parameter<(db.TimestampTzString | Date)> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, (db.TimestampTzString | Date) | db.Parameter<(db.TimestampTzString | Date)> | db.SQLFragment | db.ParentColumn>;
      /**
      * **admin_actions.description**
      * - `text` in database
      * - Nullable, no default
      */
      description?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
      /**
      * **admin_actions.id**
      * - `uuid` in database
      * - `NOT NULL`, default: `uuid_generate_v4()`
      */
      id?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
      /**
      * **admin_actions.ondemand_rebalance_paused**
      *
      * Pause flag for on-demand rebalancing operations triggered by invoice processing
      * - `bool` in database
      * - Nullable, default: `false`
      */
      ondemand_rebalance_paused?: boolean | db.Parameter<boolean> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, boolean | db.Parameter<boolean> | db.SQLFragment | db.ParentColumn>;
      /**
      * **admin_actions.purchase_paused**
      * - `bool` in database
      * - Nullable, default: `false`
      */
      purchase_paused?: boolean | db.Parameter<boolean> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, boolean | db.Parameter<boolean> | db.SQLFragment | db.ParentColumn>;
      /**
      * **admin_actions.rebalance_paused**
      * - `bool` in database
      * - Nullable, default: `false`
      */
      rebalance_paused?: boolean | db.Parameter<boolean> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, boolean | db.Parameter<boolean> | db.SQLFragment | db.ParentColumn>;
      /**
      * **admin_actions.updated_at**
      * - `timestamptz` in database
      * - Nullable, default: `now()`
      */
      updated_at?: (db.TimestampTzString | Date) | db.Parameter<(db.TimestampTzString | Date)> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, (db.TimestampTzString | Date) | db.Parameter<(db.TimestampTzString | Date)> | db.SQLFragment | db.ParentColumn>;
    }
    export interface Insertable {
      /**
      * **admin_actions.created_at**
      * - `timestamptz` in database
      * - Nullable, default: `now()`
      */
      created_at?: (db.TimestampTzString | Date) | db.Parameter<(db.TimestampTzString | Date)> | null | db.DefaultType | db.SQLFragment;
      /**
      * **admin_actions.description**
      * - `text` in database
      * - Nullable, no default
      */
      description?: string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment;
      /**
      * **admin_actions.id**
      * - `uuid` in database
      * - `NOT NULL`, default: `uuid_generate_v4()`
      */
      id?: string | db.Parameter<string> | db.DefaultType | db.SQLFragment;
      /**
      * **admin_actions.ondemand_rebalance_paused**
      *
      * Pause flag for on-demand rebalancing operations triggered by invoice processing
      * - `bool` in database
      * - Nullable, default: `false`
      */
      ondemand_rebalance_paused?: boolean | db.Parameter<boolean> | null | db.DefaultType | db.SQLFragment;
      /**
      * **admin_actions.purchase_paused**
      * - `bool` in database
      * - Nullable, default: `false`
      */
      purchase_paused?: boolean | db.Parameter<boolean> | null | db.DefaultType | db.SQLFragment;
      /**
      * **admin_actions.rebalance_paused**
      * - `bool` in database
      * - Nullable, default: `false`
      */
      rebalance_paused?: boolean | db.Parameter<boolean> | null | db.DefaultType | db.SQLFragment;
      /**
      * **admin_actions.updated_at**
      * - `timestamptz` in database
      * - Nullable, default: `now()`
      */
      updated_at?: (db.TimestampTzString | Date) | db.Parameter<(db.TimestampTzString | Date)> | null | db.DefaultType | db.SQLFragment;
    }
    export interface Updatable {
      /**
      * **admin_actions.created_at**
      * - `timestamptz` in database
      * - Nullable, default: `now()`
      */
      created_at?: (db.TimestampTzString | Date) | db.Parameter<(db.TimestampTzString | Date)> | null | db.DefaultType | db.SQLFragment | db.SQLFragment<any, (db.TimestampTzString | Date) | db.Parameter<(db.TimestampTzString | Date)> | null | db.DefaultType | db.SQLFragment>;
      /**
      * **admin_actions.description**
      * - `text` in database
      * - Nullable, no default
      */
      description?: string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment>;
      /**
      * **admin_actions.id**
      * - `uuid` in database
      * - `NOT NULL`, default: `uuid_generate_v4()`
      */
      id?: string | db.Parameter<string> | db.DefaultType | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | db.DefaultType | db.SQLFragment>;
      /**
      * **admin_actions.ondemand_rebalance_paused**
      *
      * Pause flag for on-demand rebalancing operations triggered by invoice processing
      * - `bool` in database
      * - Nullable, default: `false`
      */
      ondemand_rebalance_paused?: boolean | db.Parameter<boolean> | null | db.DefaultType | db.SQLFragment | db.SQLFragment<any, boolean | db.Parameter<boolean> | null | db.DefaultType | db.SQLFragment>;
      /**
      * **admin_actions.purchase_paused**
      * - `bool` in database
      * - Nullable, default: `false`
      */
      purchase_paused?: boolean | db.Parameter<boolean> | null | db.DefaultType | db.SQLFragment | db.SQLFragment<any, boolean | db.Parameter<boolean> | null | db.DefaultType | db.SQLFragment>;
      /**
      * **admin_actions.rebalance_paused**
      * - `bool` in database
      * - Nullable, default: `false`
      */
      rebalance_paused?: boolean | db.Parameter<boolean> | null | db.DefaultType | db.SQLFragment | db.SQLFragment<any, boolean | db.Parameter<boolean> | null | db.DefaultType | db.SQLFragment>;
      /**
      * **admin_actions.updated_at**
      * - `timestamptz` in database
      * - Nullable, default: `now()`
      */
      updated_at?: (db.TimestampTzString | Date) | db.Parameter<(db.TimestampTzString | Date)> | null | db.DefaultType | db.SQLFragment | db.SQLFragment<any, (db.TimestampTzString | Date) | db.Parameter<(db.TimestampTzString | Date)> | null | db.DefaultType | db.SQLFragment>;
    }
    export type UniqueIndex = 'admin_actions_pkey';
    export type Column = keyof Selectable;
    export type OnlyCols<T extends readonly Column[]> = Pick<Selectable, T[number]>;
    export type SQLExpression = Table | db.ColumnNames<Updatable | (keyof Updatable)[]> | db.ColumnValues<Updatable> | Whereable | Column | db.ParentColumn | db.GenericSQLExpression;
    export type SQL = SQLExpression | SQLExpression[];
  }

  /**
   * **cex_withdrawals**
   * - Table in database
   */
  export namespace cex_withdrawals {
    export type Table = 'cex_withdrawals';
    export interface Selectable {
      /**
      * **cex_withdrawals.created_at**
      * - `timestamptz` in database
      * - `NOT NULL`, default: `now()`
      */
      created_at: Date;
      /**
      * **cex_withdrawals.id**
      * - `uuid` in database
      * - `NOT NULL`, default: `uuid_generate_v4()`
      */
      id: string;
      /**
      * **cex_withdrawals.metadata**
      * - `jsonb` in database
      * - `NOT NULL`, default: `'{}'::jsonb`
      */
      metadata: db.JSONValue;
      /**
      * **cex_withdrawals.platform**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      platform: string;
      /**
      * **cex_withdrawals.rebalance_operation_id**
      * - `uuid` in database
      * - Nullable, no default
      */
      rebalance_operation_id: string | null;
      /**
      * **cex_withdrawals.updated_at**
      * - `timestamptz` in database
      * - `NOT NULL`, default: `now()`
      */
      updated_at: Date;
    }
    export interface JSONSelectable {
      /**
      * **cex_withdrawals.created_at**
      * - `timestamptz` in database
      * - `NOT NULL`, default: `now()`
      */
      created_at: db.TimestampTzString;
      /**
      * **cex_withdrawals.id**
      * - `uuid` in database
      * - `NOT NULL`, default: `uuid_generate_v4()`
      */
      id: string;
      /**
      * **cex_withdrawals.metadata**
      * - `jsonb` in database
      * - `NOT NULL`, default: `'{}'::jsonb`
      */
      metadata: db.JSONValue;
      /**
      * **cex_withdrawals.platform**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      platform: string;
      /**
      * **cex_withdrawals.rebalance_operation_id**
      * - `uuid` in database
      * - Nullable, no default
      */
      rebalance_operation_id: string | null;
      /**
      * **cex_withdrawals.updated_at**
      * - `timestamptz` in database
      * - `NOT NULL`, default: `now()`
      */
      updated_at: db.TimestampTzString;
    }
    export interface Whereable {
      /**
      * **cex_withdrawals.created_at**
      * - `timestamptz` in database
      * - `NOT NULL`, default: `now()`
      */
      created_at?: (db.TimestampTzString | Date) | db.Parameter<(db.TimestampTzString | Date)> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, (db.TimestampTzString | Date) | db.Parameter<(db.TimestampTzString | Date)> | db.SQLFragment | db.ParentColumn>;
      /**
      * **cex_withdrawals.id**
      * - `uuid` in database
      * - `NOT NULL`, default: `uuid_generate_v4()`
      */
      id?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
      /**
      * **cex_withdrawals.metadata**
      * - `jsonb` in database
      * - `NOT NULL`, default: `'{}'::jsonb`
      */
      metadata?: db.JSONValue | db.Parameter<db.JSONValue> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, db.JSONValue | db.Parameter<db.JSONValue> | db.SQLFragment | db.ParentColumn>;
      /**
      * **cex_withdrawals.platform**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      platform?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
      /**
      * **cex_withdrawals.rebalance_operation_id**
      * - `uuid` in database
      * - Nullable, no default
      */
      rebalance_operation_id?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
      /**
      * **cex_withdrawals.updated_at**
      * - `timestamptz` in database
      * - `NOT NULL`, default: `now()`
      */
      updated_at?: (db.TimestampTzString | Date) | db.Parameter<(db.TimestampTzString | Date)> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, (db.TimestampTzString | Date) | db.Parameter<(db.TimestampTzString | Date)> | db.SQLFragment | db.ParentColumn>;
    }
    export interface Insertable {
      /**
      * **cex_withdrawals.created_at**
      * - `timestamptz` in database
      * - `NOT NULL`, default: `now()`
      */
      created_at?: (db.TimestampTzString | Date) | db.Parameter<(db.TimestampTzString | Date)> | db.DefaultType | db.SQLFragment;
      /**
      * **cex_withdrawals.id**
      * - `uuid` in database
      * - `NOT NULL`, default: `uuid_generate_v4()`
      */
      id?: string | db.Parameter<string> | db.DefaultType | db.SQLFragment;
      /**
      * **cex_withdrawals.metadata**
      * - `jsonb` in database
      * - `NOT NULL`, default: `'{}'::jsonb`
      */
      metadata?: db.JSONValue | db.Parameter<db.JSONValue> | db.DefaultType | db.SQLFragment;
      /**
      * **cex_withdrawals.platform**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      platform: string | db.Parameter<string> | db.SQLFragment;
      /**
      * **cex_withdrawals.rebalance_operation_id**
      * - `uuid` in database
      * - Nullable, no default
      */
      rebalance_operation_id?: string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment;
      /**
      * **cex_withdrawals.updated_at**
      * - `timestamptz` in database
      * - `NOT NULL`, default: `now()`
      */
      updated_at?: (db.TimestampTzString | Date) | db.Parameter<(db.TimestampTzString | Date)> | db.DefaultType | db.SQLFragment;
    }
    export interface Updatable {
      /**
      * **cex_withdrawals.created_at**
      * - `timestamptz` in database
      * - `NOT NULL`, default: `now()`
      */
      created_at?: (db.TimestampTzString | Date) | db.Parameter<(db.TimestampTzString | Date)> | db.DefaultType | db.SQLFragment | db.SQLFragment<any, (db.TimestampTzString | Date) | db.Parameter<(db.TimestampTzString | Date)> | db.DefaultType | db.SQLFragment>;
      /**
      * **cex_withdrawals.id**
      * - `uuid` in database
      * - `NOT NULL`, default: `uuid_generate_v4()`
      */
      id?: string | db.Parameter<string> | db.DefaultType | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | db.DefaultType | db.SQLFragment>;
      /**
      * **cex_withdrawals.metadata**
      * - `jsonb` in database
      * - `NOT NULL`, default: `'{}'::jsonb`
      */
      metadata?: db.JSONValue | db.Parameter<db.JSONValue> | db.DefaultType | db.SQLFragment | db.SQLFragment<any, db.JSONValue | db.Parameter<db.JSONValue> | db.DefaultType | db.SQLFragment>;
      /**
      * **cex_withdrawals.platform**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      platform?: string | db.Parameter<string> | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment>;
      /**
      * **cex_withdrawals.rebalance_operation_id**
      * - `uuid` in database
      * - Nullable, no default
      */
      rebalance_operation_id?: string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment>;
      /**
      * **cex_withdrawals.updated_at**
      * - `timestamptz` in database
      * - `NOT NULL`, default: `now()`
      */
      updated_at?: (db.TimestampTzString | Date) | db.Parameter<(db.TimestampTzString | Date)> | db.DefaultType | db.SQLFragment | db.SQLFragment<any, (db.TimestampTzString | Date) | db.Parameter<(db.TimestampTzString | Date)> | db.DefaultType | db.SQLFragment>;
    }
    export type UniqueIndex = 'cex_withdrawals_pkey';
    export type Column = keyof Selectable;
    export type OnlyCols<T extends readonly Column[]> = Pick<Selectable, T[number]>;
    export type SQLExpression = Table | db.ColumnNames<Updatable | (keyof Updatable)[]> | db.ColumnValues<Updatable> | Whereable | Column | db.ParentColumn | db.GenericSQLExpression;
    export type SQL = SQLExpression | SQLExpression[];
  }

  /**
   * **earmarks**
   * - Table in database
   */
  export namespace earmarks {
    export type Table = 'earmarks';
    export interface Selectable {
      /**
      * **earmarks.created_at**
      * - `timestamptz` in database
      * - Nullable, default: `now()`
      */
      created_at: Date | null;
      /**
      * **earmarks.designated_purchase_chain**
      *
      * Designated chain ID for purchasing this invoice - the invoice destination chain that Mark has identified as the target for fund aggregation
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      designated_purchase_chain: number;
      /**
      * **earmarks.id**
      * - `uuid` in database
      * - `NOT NULL`, default: `uuid_generate_v4()`
      */
      id: string;
      /**
      * **earmarks.invoice_id**
      *
      * External invoice identifier from the invoice processing system
      * - `text` in database
      * - `NOT NULL`, no default
      */
      invoice_id: string;
      /**
      * **earmarks.min_amount**
      *
      * Minimum amount of tokens required for invoice payment on the designated chain (stored as string to preserve precision)
      * - `text` in database
      * - `NOT NULL`, no default
      */
      min_amount: string;
      /**
      * **earmarks.status**
      *
      * Earmark status: pending, ready, completed, cancelled, failed, expired (enforced by CHECK constraint)
      * - `text` in database
      * - `NOT NULL`, default: `'pending'::text`
      */
      status: string;
      /**
      * **earmarks.ticker_hash**
      *
      * Token ticker_hash (e.g., USDC, ETH) required for invoice payment
      * - `text` in database
      * - `NOT NULL`, no default
      */
      ticker_hash: string;
      /**
      * **earmarks.updated_at**
      * - `timestamptz` in database
      * - Nullable, default: `now()`
      */
      updated_at: Date | null;
    }
    export interface JSONSelectable {
      /**
      * **earmarks.created_at**
      * - `timestamptz` in database
      * - Nullable, default: `now()`
      */
      created_at: db.TimestampTzString | null;
      /**
      * **earmarks.designated_purchase_chain**
      *
      * Designated chain ID for purchasing this invoice - the invoice destination chain that Mark has identified as the target for fund aggregation
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      designated_purchase_chain: number;
      /**
      * **earmarks.id**
      * - `uuid` in database
      * - `NOT NULL`, default: `uuid_generate_v4()`
      */
      id: string;
      /**
      * **earmarks.invoice_id**
      *
      * External invoice identifier from the invoice processing system
      * - `text` in database
      * - `NOT NULL`, no default
      */
      invoice_id: string;
      /**
      * **earmarks.min_amount**
      *
      * Minimum amount of tokens required for invoice payment on the designated chain (stored as string to preserve precision)
      * - `text` in database
      * - `NOT NULL`, no default
      */
      min_amount: string;
      /**
      * **earmarks.status**
      *
      * Earmark status: pending, ready, completed, cancelled, failed, expired (enforced by CHECK constraint)
      * - `text` in database
      * - `NOT NULL`, default: `'pending'::text`
      */
      status: string;
      /**
      * **earmarks.ticker_hash**
      *
      * Token ticker_hash (e.g., USDC, ETH) required for invoice payment
      * - `text` in database
      * - `NOT NULL`, no default
      */
      ticker_hash: string;
      /**
      * **earmarks.updated_at**
      * - `timestamptz` in database
      * - Nullable, default: `now()`
      */
      updated_at: db.TimestampTzString | null;
    }
    export interface Whereable {
      /**
      * **earmarks.created_at**
      * - `timestamptz` in database
      * - Nullable, default: `now()`
      */
      created_at?: (db.TimestampTzString | Date) | db.Parameter<(db.TimestampTzString | Date)> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, (db.TimestampTzString | Date) | db.Parameter<(db.TimestampTzString | Date)> | db.SQLFragment | db.ParentColumn>;
      /**
      * **earmarks.designated_purchase_chain**
      *
      * Designated chain ID for purchasing this invoice - the invoice destination chain that Mark has identified as the target for fund aggregation
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      designated_purchase_chain?: number | db.Parameter<number> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, number | db.Parameter<number> | db.SQLFragment | db.ParentColumn>;
      /**
      * **earmarks.id**
      * - `uuid` in database
      * - `NOT NULL`, default: `uuid_generate_v4()`
      */
      id?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
      /**
      * **earmarks.invoice_id**
      *
      * External invoice identifier from the invoice processing system
      * - `text` in database
      * - `NOT NULL`, no default
      */
      invoice_id?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
      /**
      * **earmarks.min_amount**
      *
      * Minimum amount of tokens required for invoice payment on the designated chain (stored as string to preserve precision)
      * - `text` in database
      * - `NOT NULL`, no default
      */
      min_amount?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
      /**
      * **earmarks.status**
      *
      * Earmark status: pending, ready, completed, cancelled, failed, expired (enforced by CHECK constraint)
      * - `text` in database
      * - `NOT NULL`, default: `'pending'::text`
      */
      status?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
      /**
      * **earmarks.ticker_hash**
      *
      * Token ticker_hash (e.g., USDC, ETH) required for invoice payment
      * - `text` in database
      * - `NOT NULL`, no default
      */
      ticker_hash?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
      /**
      * **earmarks.updated_at**
      * - `timestamptz` in database
      * - Nullable, default: `now()`
      */
      updated_at?: (db.TimestampTzString | Date) | db.Parameter<(db.TimestampTzString | Date)> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, (db.TimestampTzString | Date) | db.Parameter<(db.TimestampTzString | Date)> | db.SQLFragment | db.ParentColumn>;
    }
    export interface Insertable {
      /**
      * **earmarks.created_at**
      * - `timestamptz` in database
      * - Nullable, default: `now()`
      */
      created_at?: (db.TimestampTzString | Date) | db.Parameter<(db.TimestampTzString | Date)> | null | db.DefaultType | db.SQLFragment;
      /**
      * **earmarks.designated_purchase_chain**
      *
      * Designated chain ID for purchasing this invoice - the invoice destination chain that Mark has identified as the target for fund aggregation
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      designated_purchase_chain: number | db.Parameter<number> | db.SQLFragment;
      /**
      * **earmarks.id**
      * - `uuid` in database
      * - `NOT NULL`, default: `uuid_generate_v4()`
      */
      id?: string | db.Parameter<string> | db.DefaultType | db.SQLFragment;
      /**
      * **earmarks.invoice_id**
      *
      * External invoice identifier from the invoice processing system
      * - `text` in database
      * - `NOT NULL`, no default
      */
      invoice_id: string | db.Parameter<string> | db.SQLFragment;
      /**
      * **earmarks.min_amount**
      *
      * Minimum amount of tokens required for invoice payment on the designated chain (stored as string to preserve precision)
      * - `text` in database
      * - `NOT NULL`, no default
      */
      min_amount: string | db.Parameter<string> | db.SQLFragment;
      /**
      * **earmarks.status**
      *
      * Earmark status: pending, ready, completed, cancelled, failed, expired (enforced by CHECK constraint)
      * - `text` in database
      * - `NOT NULL`, default: `'pending'::text`
      */
      status?: string | db.Parameter<string> | db.DefaultType | db.SQLFragment;
      /**
      * **earmarks.ticker_hash**
      *
      * Token ticker_hash (e.g., USDC, ETH) required for invoice payment
      * - `text` in database
      * - `NOT NULL`, no default
      */
      ticker_hash: string | db.Parameter<string> | db.SQLFragment;
      /**
      * **earmarks.updated_at**
      * - `timestamptz` in database
      * - Nullable, default: `now()`
      */
      updated_at?: (db.TimestampTzString | Date) | db.Parameter<(db.TimestampTzString | Date)> | null | db.DefaultType | db.SQLFragment;
    }
    export interface Updatable {
      /**
      * **earmarks.created_at**
      * - `timestamptz` in database
      * - Nullable, default: `now()`
      */
      created_at?: (db.TimestampTzString | Date) | db.Parameter<(db.TimestampTzString | Date)> | null | db.DefaultType | db.SQLFragment | db.SQLFragment<any, (db.TimestampTzString | Date) | db.Parameter<(db.TimestampTzString | Date)> | null | db.DefaultType | db.SQLFragment>;
      /**
      * **earmarks.designated_purchase_chain**
      *
      * Designated chain ID for purchasing this invoice - the invoice destination chain that Mark has identified as the target for fund aggregation
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      designated_purchase_chain?: number | db.Parameter<number> | db.SQLFragment | db.SQLFragment<any, number | db.Parameter<number> | db.SQLFragment>;
      /**
      * **earmarks.id**
      * - `uuid` in database
      * - `NOT NULL`, default: `uuid_generate_v4()`
      */
      id?: string | db.Parameter<string> | db.DefaultType | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | db.DefaultType | db.SQLFragment>;
      /**
      * **earmarks.invoice_id**
      *
      * External invoice identifier from the invoice processing system
      * - `text` in database
      * - `NOT NULL`, no default
      */
      invoice_id?: string | db.Parameter<string> | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment>;
      /**
      * **earmarks.min_amount**
      *
      * Minimum amount of tokens required for invoice payment on the designated chain (stored as string to preserve precision)
      * - `text` in database
      * - `NOT NULL`, no default
      */
      min_amount?: string | db.Parameter<string> | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment>;
      /**
      * **earmarks.status**
      *
      * Earmark status: pending, ready, completed, cancelled, failed, expired (enforced by CHECK constraint)
      * - `text` in database
      * - `NOT NULL`, default: `'pending'::text`
      */
      status?: string | db.Parameter<string> | db.DefaultType | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | db.DefaultType | db.SQLFragment>;
      /**
      * **earmarks.ticker_hash**
      *
      * Token ticker_hash (e.g., USDC, ETH) required for invoice payment
      * - `text` in database
      * - `NOT NULL`, no default
      */
      ticker_hash?: string | db.Parameter<string> | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment>;
      /**
      * **earmarks.updated_at**
      * - `timestamptz` in database
      * - Nullable, default: `now()`
      */
      updated_at?: (db.TimestampTzString | Date) | db.Parameter<(db.TimestampTzString | Date)> | null | db.DefaultType | db.SQLFragment | db.SQLFragment<any, (db.TimestampTzString | Date) | db.Parameter<(db.TimestampTzString | Date)> | null | db.DefaultType | db.SQLFragment>;
    }
    export type UniqueIndex = 'earmarks_pkey' | 'unique_active_earmark_per_invoice';
    export type Column = keyof Selectable;
    export type OnlyCols<T extends readonly Column[]> = Pick<Selectable, T[number]>;
    export type SQLExpression = Table | db.ColumnNames<Updatable | (keyof Updatable)[]> | db.ColumnValues<Updatable> | Whereable | Column | db.ParentColumn | db.GenericSQLExpression;
    export type SQL = SQLExpression | SQLExpression[];
  }

  /**
   * **rebalance_operations**
   * - Table in database
   */
  export namespace rebalance_operations {
    export type Table = 'rebalance_operations';
    export interface Selectable {
      /**
      * **rebalance_operations.amount**
      *
      * Amount of tokens being rebalanced (stored as string to preserve precision)
      * - `text` in database
      * - `NOT NULL`, no default
      */
      amount: string;
      /**
      * **rebalance_operations.bridge**
      *
      * Bridge adapter type used for this operation (e.g., across, binance)
      * - `text` in database
      * - Nullable, no default
      */
      bridge: string | null;
      /**
      * **rebalance_operations.created_at**
      * - `timestamptz` in database
      * - Nullable, default: `now()`
      */
      created_at: Date | null;
      /**
      * **rebalance_operations.destination_chain_id**
      *
      * Target chain ID where funds are being moved to
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      destination_chain_id: number;
      /**
      * **rebalance_operations.earmark_id**
      *
      * Foreign key to the earmark this operation fulfills (NULL for regular rebalancing)
      * - `uuid` in database
      * - Nullable, no default
      */
      earmark_id: string | null;
      /**
      * **rebalance_operations.id**
      * - `uuid` in database
      * - `NOT NULL`, default: `uuid_generate_v4()`
      */
      id: string;
      /**
      * **rebalance_operations.is_orphaned**
      *
      * Indicates if this operation was orphaned when its associated earmark was cancelled
      * - `bool` in database
      * - `NOT NULL`, default: `false`
      */
      is_orphaned: boolean;
      /**
      * **rebalance_operations.metadata**
      *
      * Bridge-specific metadata (e.g., CEX withdrawal details, bridge transaction IDs)
      * - `jsonb` in database
      * - `NOT NULL`, default: `'{}'::jsonb`
      */
      metadata: db.JSONValue;
      /**
      * **rebalance_operations.origin_chain_id**
      *
      * Source chain ID where funds are being moved from
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      origin_chain_id: number;
      /**
      * **rebalance_operations.recipient**
      *
      * Recipient address for the rebalance operation (destination address on target chain)
      * - `text` in database
      * - Nullable, no default
      */
      recipient: string | null;
      /**
      * **rebalance_operations.slippage**
      *
      * Expected slippage in basis points (e.g., 30 = 0.3%)
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      slippage: number;
      /**
      * **rebalance_operations.status**
      *
      * Operation status: pending, awaiting_callback, completed, expired, cancelled (enforced by CHECK constraint)
      * - `text` in database
      * - `NOT NULL`, default: `'pending'::text`
      */
      status: string;
      /**
      * **rebalance_operations.ticker_hash**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      ticker_hash: string;
      /**
      * **rebalance_operations.updated_at**
      * - `timestamptz` in database
      * - Nullable, default: `now()`
      */
      updated_at: Date | null;
    }
    export interface JSONSelectable {
      /**
      * **rebalance_operations.amount**
      *
      * Amount of tokens being rebalanced (stored as string to preserve precision)
      * - `text` in database
      * - `NOT NULL`, no default
      */
      amount: string;
      /**
      * **rebalance_operations.bridge**
      *
      * Bridge adapter type used for this operation (e.g., across, binance)
      * - `text` in database
      * - Nullable, no default
      */
      bridge: string | null;
      /**
      * **rebalance_operations.created_at**
      * - `timestamptz` in database
      * - Nullable, default: `now()`
      */
      created_at: db.TimestampTzString | null;
      /**
      * **rebalance_operations.destination_chain_id**
      *
      * Target chain ID where funds are being moved to
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      destination_chain_id: number;
      /**
      * **rebalance_operations.earmark_id**
      *
      * Foreign key to the earmark this operation fulfills (NULL for regular rebalancing)
      * - `uuid` in database
      * - Nullable, no default
      */
      earmark_id: string | null;
      /**
      * **rebalance_operations.id**
      * - `uuid` in database
      * - `NOT NULL`, default: `uuid_generate_v4()`
      */
      id: string;
      /**
      * **rebalance_operations.is_orphaned**
      *
      * Indicates if this operation was orphaned when its associated earmark was cancelled
      * - `bool` in database
      * - `NOT NULL`, default: `false`
      */
      is_orphaned: boolean;
      /**
      * **rebalance_operations.metadata**
      *
      * Bridge-specific metadata (e.g., CEX withdrawal details, bridge transaction IDs)
      * - `jsonb` in database
      * - `NOT NULL`, default: `'{}'::jsonb`
      */
      metadata: db.JSONValue;
      /**
      * **rebalance_operations.origin_chain_id**
      *
      * Source chain ID where funds are being moved from
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      origin_chain_id: number;
      /**
      * **rebalance_operations.recipient**
      *
      * Recipient address for the rebalance operation (destination address on target chain)
      * - `text` in database
      * - Nullable, no default
      */
      recipient: string | null;
      /**
      * **rebalance_operations.slippage**
      *
      * Expected slippage in basis points (e.g., 30 = 0.3%)
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      slippage: number;
      /**
      * **rebalance_operations.status**
      *
      * Operation status: pending, awaiting_callback, completed, expired, cancelled (enforced by CHECK constraint)
      * - `text` in database
      * - `NOT NULL`, default: `'pending'::text`
      */
      status: string;
      /**
      * **rebalance_operations.ticker_hash**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      ticker_hash: string;
      /**
      * **rebalance_operations.updated_at**
      * - `timestamptz` in database
      * - Nullable, default: `now()`
      */
      updated_at: db.TimestampTzString | null;
    }
    export interface Whereable {
      /**
      * **rebalance_operations.amount**
      *
      * Amount of tokens being rebalanced (stored as string to preserve precision)
      * - `text` in database
      * - `NOT NULL`, no default
      */
      amount?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
      /**
      * **rebalance_operations.bridge**
      *
      * Bridge adapter type used for this operation (e.g., across, binance)
      * - `text` in database
      * - Nullable, no default
      */
      bridge?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
      /**
      * **rebalance_operations.created_at**
      * - `timestamptz` in database
      * - Nullable, default: `now()`
      */
      created_at?: (db.TimestampTzString | Date) | db.Parameter<(db.TimestampTzString | Date)> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, (db.TimestampTzString | Date) | db.Parameter<(db.TimestampTzString | Date)> | db.SQLFragment | db.ParentColumn>;
      /**
      * **rebalance_operations.destination_chain_id**
      *
      * Target chain ID where funds are being moved to
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      destination_chain_id?: number | db.Parameter<number> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, number | db.Parameter<number> | db.SQLFragment | db.ParentColumn>;
      /**
      * **rebalance_operations.earmark_id**
      *
      * Foreign key to the earmark this operation fulfills (NULL for regular rebalancing)
      * - `uuid` in database
      * - Nullable, no default
      */
      earmark_id?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
      /**
      * **rebalance_operations.id**
      * - `uuid` in database
      * - `NOT NULL`, default: `uuid_generate_v4()`
      */
      id?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
      /**
      * **rebalance_operations.is_orphaned**
      *
      * Indicates if this operation was orphaned when its associated earmark was cancelled
      * - `bool` in database
      * - `NOT NULL`, default: `false`
      */
      is_orphaned?: boolean | db.Parameter<boolean> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, boolean | db.Parameter<boolean> | db.SQLFragment | db.ParentColumn>;
      /**
      * **rebalance_operations.metadata**
      *
      * Bridge-specific metadata (e.g., CEX withdrawal details, bridge transaction IDs)
      * - `jsonb` in database
      * - `NOT NULL`, default: `'{}'::jsonb`
      */
      metadata?: db.JSONValue | db.Parameter<db.JSONValue> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, db.JSONValue | db.Parameter<db.JSONValue> | db.SQLFragment | db.ParentColumn>;
      /**
      * **rebalance_operations.origin_chain_id**
      *
      * Source chain ID where funds are being moved from
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      origin_chain_id?: number | db.Parameter<number> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, number | db.Parameter<number> | db.SQLFragment | db.ParentColumn>;
      /**
      * **rebalance_operations.recipient**
      *
      * Recipient address for the rebalance operation (destination address on target chain)
      * - `text` in database
      * - Nullable, no default
      */
      recipient?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
      /**
      * **rebalance_operations.slippage**
      *
      * Expected slippage in basis points (e.g., 30 = 0.3%)
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      slippage?: number | db.Parameter<number> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, number | db.Parameter<number> | db.SQLFragment | db.ParentColumn>;
      /**
      * **rebalance_operations.status**
      *
      * Operation status: pending, awaiting_callback, completed, expired, cancelled (enforced by CHECK constraint)
      * - `text` in database
      * - `NOT NULL`, default: `'pending'::text`
      */
      status?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
      /**
      * **rebalance_operations.ticker_hash**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      ticker_hash?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
      /**
      * **rebalance_operations.updated_at**
      * - `timestamptz` in database
      * - Nullable, default: `now()`
      */
      updated_at?: (db.TimestampTzString | Date) | db.Parameter<(db.TimestampTzString | Date)> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, (db.TimestampTzString | Date) | db.Parameter<(db.TimestampTzString | Date)> | db.SQLFragment | db.ParentColumn>;
    }
    export interface Insertable {
      /**
      * **rebalance_operations.amount**
      *
      * Amount of tokens being rebalanced (stored as string to preserve precision)
      * - `text` in database
      * - `NOT NULL`, no default
      */
      amount: string | db.Parameter<string> | db.SQLFragment;
      /**
      * **rebalance_operations.bridge**
      *
      * Bridge adapter type used for this operation (e.g., across, binance)
      * - `text` in database
      * - Nullable, no default
      */
      bridge?: string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment;
      /**
      * **rebalance_operations.created_at**
      * - `timestamptz` in database
      * - Nullable, default: `now()`
      */
      created_at?: (db.TimestampTzString | Date) | db.Parameter<(db.TimestampTzString | Date)> | null | db.DefaultType | db.SQLFragment;
      /**
      * **rebalance_operations.destination_chain_id**
      *
      * Target chain ID where funds are being moved to
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      destination_chain_id: number | db.Parameter<number> | db.SQLFragment;
      /**
      * **rebalance_operations.earmark_id**
      *
      * Foreign key to the earmark this operation fulfills (NULL for regular rebalancing)
      * - `uuid` in database
      * - Nullable, no default
      */
      earmark_id?: string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment;
      /**
      * **rebalance_operations.id**
      * - `uuid` in database
      * - `NOT NULL`, default: `uuid_generate_v4()`
      */
      id?: string | db.Parameter<string> | db.DefaultType | db.SQLFragment;
      /**
      * **rebalance_operations.is_orphaned**
      *
      * Indicates if this operation was orphaned when its associated earmark was cancelled
      * - `bool` in database
      * - `NOT NULL`, default: `false`
      */
      is_orphaned?: boolean | db.Parameter<boolean> | db.DefaultType | db.SQLFragment;
      /**
      * **rebalance_operations.metadata**
      *
      * Bridge-specific metadata (e.g., CEX withdrawal details, bridge transaction IDs)
      * - `jsonb` in database
      * - `NOT NULL`, default: `'{}'::jsonb`
      */
      metadata?: db.JSONValue | db.Parameter<db.JSONValue> | db.DefaultType | db.SQLFragment;
      /**
      * **rebalance_operations.origin_chain_id**
      *
      * Source chain ID where funds are being moved from
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      origin_chain_id: number | db.Parameter<number> | db.SQLFragment;
      /**
      * **rebalance_operations.recipient**
      *
      * Recipient address for the rebalance operation (destination address on target chain)
      * - `text` in database
      * - Nullable, no default
      */
      recipient?: string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment;
      /**
      * **rebalance_operations.slippage**
      *
      * Expected slippage in basis points (e.g., 30 = 0.3%)
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      slippage: number | db.Parameter<number> | db.SQLFragment;
      /**
      * **rebalance_operations.status**
      *
      * Operation status: pending, awaiting_callback, completed, expired, cancelled (enforced by CHECK constraint)
      * - `text` in database
      * - `NOT NULL`, default: `'pending'::text`
      */
      status?: string | db.Parameter<string> | db.DefaultType | db.SQLFragment;
      /**
      * **rebalance_operations.ticker_hash**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      ticker_hash: string | db.Parameter<string> | db.SQLFragment;
      /**
      * **rebalance_operations.updated_at**
      * - `timestamptz` in database
      * - Nullable, default: `now()`
      */
      updated_at?: (db.TimestampTzString | Date) | db.Parameter<(db.TimestampTzString | Date)> | null | db.DefaultType | db.SQLFragment;
    }
    export interface Updatable {
      /**
      * **rebalance_operations.amount**
      *
      * Amount of tokens being rebalanced (stored as string to preserve precision)
      * - `text` in database
      * - `NOT NULL`, no default
      */
      amount?: string | db.Parameter<string> | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment>;
      /**
      * **rebalance_operations.bridge**
      *
      * Bridge adapter type used for this operation (e.g., across, binance)
      * - `text` in database
      * - Nullable, no default
      */
      bridge?: string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment>;
      /**
      * **rebalance_operations.created_at**
      * - `timestamptz` in database
      * - Nullable, default: `now()`
      */
      created_at?: (db.TimestampTzString | Date) | db.Parameter<(db.TimestampTzString | Date)> | null | db.DefaultType | db.SQLFragment | db.SQLFragment<any, (db.TimestampTzString | Date) | db.Parameter<(db.TimestampTzString | Date)> | null | db.DefaultType | db.SQLFragment>;
      /**
      * **rebalance_operations.destination_chain_id**
      *
      * Target chain ID where funds are being moved to
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      destination_chain_id?: number | db.Parameter<number> | db.SQLFragment | db.SQLFragment<any, number | db.Parameter<number> | db.SQLFragment>;
      /**
      * **rebalance_operations.earmark_id**
      *
      * Foreign key to the earmark this operation fulfills (NULL for regular rebalancing)
      * - `uuid` in database
      * - Nullable, no default
      */
      earmark_id?: string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment>;
      /**
      * **rebalance_operations.id**
      * - `uuid` in database
      * - `NOT NULL`, default: `uuid_generate_v4()`
      */
      id?: string | db.Parameter<string> | db.DefaultType | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | db.DefaultType | db.SQLFragment>;
      /**
      * **rebalance_operations.is_orphaned**
      *
      * Indicates if this operation was orphaned when its associated earmark was cancelled
      * - `bool` in database
      * - `NOT NULL`, default: `false`
      */
      is_orphaned?: boolean | db.Parameter<boolean> | db.DefaultType | db.SQLFragment | db.SQLFragment<any, boolean | db.Parameter<boolean> | db.DefaultType | db.SQLFragment>;
      /**
      * **rebalance_operations.metadata**
      *
      * Bridge-specific metadata (e.g., CEX withdrawal details, bridge transaction IDs)
      * - `jsonb` in database
      * - `NOT NULL`, default: `'{}'::jsonb`
      */
      metadata?: db.JSONValue | db.Parameter<db.JSONValue> | db.DefaultType | db.SQLFragment | db.SQLFragment<any, db.JSONValue | db.Parameter<db.JSONValue> | db.DefaultType | db.SQLFragment>;
      /**
      * **rebalance_operations.origin_chain_id**
      *
      * Source chain ID where funds are being moved from
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      origin_chain_id?: number | db.Parameter<number> | db.SQLFragment | db.SQLFragment<any, number | db.Parameter<number> | db.SQLFragment>;
      /**
      * **rebalance_operations.recipient**
      *
      * Recipient address for the rebalance operation (destination address on target chain)
      * - `text` in database
      * - Nullable, no default
      */
      recipient?: string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment>;
      /**
      * **rebalance_operations.slippage**
      *
      * Expected slippage in basis points (e.g., 30 = 0.3%)
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      slippage?: number | db.Parameter<number> | db.SQLFragment | db.SQLFragment<any, number | db.Parameter<number> | db.SQLFragment>;
      /**
      * **rebalance_operations.status**
      *
      * Operation status: pending, awaiting_callback, completed, expired, cancelled (enforced by CHECK constraint)
      * - `text` in database
      * - `NOT NULL`, default: `'pending'::text`
      */
      status?: string | db.Parameter<string> | db.DefaultType | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | db.DefaultType | db.SQLFragment>;
      /**
      * **rebalance_operations.ticker_hash**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      ticker_hash?: string | db.Parameter<string> | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment>;
      /**
      * **rebalance_operations.updated_at**
      * - `timestamptz` in database
      * - Nullable, default: `now()`
      */
      updated_at?: (db.TimestampTzString | Date) | db.Parameter<(db.TimestampTzString | Date)> | null | db.DefaultType | db.SQLFragment | db.SQLFragment<any, (db.TimestampTzString | Date) | db.Parameter<(db.TimestampTzString | Date)> | null | db.DefaultType | db.SQLFragment>;
    }
    export type UniqueIndex = 'rebalance_operations_pkey';
    export type Column = keyof Selectable;
    export type OnlyCols<T extends readonly Column[]> = Pick<Selectable, T[number]>;
    export type SQLExpression = Table | db.ColumnNames<Updatable | (keyof Updatable)[]> | db.ColumnValues<Updatable> | Whereable | Column | db.ParentColumn | db.GenericSQLExpression;
    export type SQL = SQLExpression | SQLExpression[];
  }

  /**
   * **schema_migrations**
   * - Table in database
   */
  export namespace schema_migrations {
    export type Table = 'schema_migrations';
    export interface Selectable {
      /**
      * **schema_migrations.version**
      * - `varchar` in database
      * - `NOT NULL`, no default
      */
      version: string;
    }
    export interface JSONSelectable {
      /**
      * **schema_migrations.version**
      * - `varchar` in database
      * - `NOT NULL`, no default
      */
      version: string;
    }
    export interface Whereable {
      /**
      * **schema_migrations.version**
      * - `varchar` in database
      * - `NOT NULL`, no default
      */
      version?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
    }
    export interface Insertable {
      /**
      * **schema_migrations.version**
      * - `varchar` in database
      * - `NOT NULL`, no default
      */
      version: string | db.Parameter<string> | db.SQLFragment;
    }
    export interface Updatable {
      /**
      * **schema_migrations.version**
      * - `varchar` in database
      * - `NOT NULL`, no default
      */
      version?: string | db.Parameter<string> | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment>;
    }
    export type UniqueIndex = 'schema_migrations_pkey';
    export type Column = keyof Selectable;
    export type OnlyCols<T extends readonly Column[]> = Pick<Selectable, T[number]>;
    export type SQLExpression = Table | db.ColumnNames<Updatable | (keyof Updatable)[]> | db.ColumnValues<Updatable> | Whereable | Column | db.ParentColumn | db.GenericSQLExpression;
    export type SQL = SQLExpression | SQLExpression[];
  }

  /**
   * **transactions**
   * - Table in database
   */
  export namespace transactions {
    export type Table = 'transactions';
    export interface Selectable {
      /**
      * **transactions.chain_id**
      *
      * Chain ID where transaction occurred (stored as text for large chain IDs)
      * - `text` in database
      * - `NOT NULL`, no default
      */
      chain_id: string;
      /**
      * **transactions.created_at**
      * - `timestamptz` in database
      * - `NOT NULL`, default: `now()`
      */
      created_at: Date;
      /**
      * **transactions.cumulative_gas_used**
      *
      * Total gas used by transaction (stored as text for precision)
      * - `text` in database
      * - `NOT NULL`, no default
      */
      cumulative_gas_used: string;
      /**
      * **transactions.effective_gas_price**
      *
      * Effective gas price paid (stored as text for precision)
      * - `text` in database
      * - `NOT NULL`, no default
      */
      effective_gas_price: string;
      /**
      * **transactions.from**
      *
      * Transaction sender address
      * - `text` in database
      * - `NOT NULL`, no default
      */
      from: string;
      /**
      * **transactions.id**
      * - `uuid` in database
      * - `NOT NULL`, default: `uuid_generate_v4()`
      */
      id: string;
      /**
      * **transactions.metadata**
      *
      * Additional transaction-specific data stored as JSON
      * - `jsonb` in database
      * - Nullable, default: `'{}'::jsonb`
      */
      metadata: db.JSONValue | null;
      /**
      * **transactions.reason**
      *
      * Transaction purpose/category (e.g., deposit, withdrawal, bridge, etc.)
      * - `text` in database
      * - `NOT NULL`, no default
      */
      reason: string;
      /**
      * **transactions.rebalance_operation_id**
      *
      * Optional reference to associated rebalance operation (NULL for standalone transactions)
      * - `uuid` in database
      * - Nullable, no default
      */
      rebalance_operation_id: string | null;
      /**
      * **transactions.to**
      *
      * Transaction destination address
      * - `text` in database
      * - `NOT NULL`, no default
      */
      to: string;
      /**
      * **transactions.transaction_hash**
      *
      * On-chain transaction hash
      * - `text` in database
      * - `NOT NULL`, no default
      */
      transaction_hash: string;
      /**
      * **transactions.updated_at**
      * - `timestamptz` in database
      * - `NOT NULL`, default: `now()`
      */
      updated_at: Date;
    }
    export interface JSONSelectable {
      /**
      * **transactions.chain_id**
      *
      * Chain ID where transaction occurred (stored as text for large chain IDs)
      * - `text` in database
      * - `NOT NULL`, no default
      */
      chain_id: string;
      /**
      * **transactions.created_at**
      * - `timestamptz` in database
      * - `NOT NULL`, default: `now()`
      */
      created_at: db.TimestampTzString;
      /**
      * **transactions.cumulative_gas_used**
      *
      * Total gas used by transaction (stored as text for precision)
      * - `text` in database
      * - `NOT NULL`, no default
      */
      cumulative_gas_used: string;
      /**
      * **transactions.effective_gas_price**
      *
      * Effective gas price paid (stored as text for precision)
      * - `text` in database
      * - `NOT NULL`, no default
      */
      effective_gas_price: string;
      /**
      * **transactions.from**
      *
      * Transaction sender address
      * - `text` in database
      * - `NOT NULL`, no default
      */
      from: string;
      /**
      * **transactions.id**
      * - `uuid` in database
      * - `NOT NULL`, default: `uuid_generate_v4()`
      */
      id: string;
      /**
      * **transactions.metadata**
      *
      * Additional transaction-specific data stored as JSON
      * - `jsonb` in database
      * - Nullable, default: `'{}'::jsonb`
      */
      metadata: db.JSONValue | null;
      /**
      * **transactions.reason**
      *
      * Transaction purpose/category (e.g., deposit, withdrawal, bridge, etc.)
      * - `text` in database
      * - `NOT NULL`, no default
      */
      reason: string;
      /**
      * **transactions.rebalance_operation_id**
      *
      * Optional reference to associated rebalance operation (NULL for standalone transactions)
      * - `uuid` in database
      * - Nullable, no default
      */
      rebalance_operation_id: string | null;
      /**
      * **transactions.to**
      *
      * Transaction destination address
      * - `text` in database
      * - `NOT NULL`, no default
      */
      to: string;
      /**
      * **transactions.transaction_hash**
      *
      * On-chain transaction hash
      * - `text` in database
      * - `NOT NULL`, no default
      */
      transaction_hash: string;
      /**
      * **transactions.updated_at**
      * - `timestamptz` in database
      * - `NOT NULL`, default: `now()`
      */
      updated_at: db.TimestampTzString;
    }
    export interface Whereable {
      /**
      * **transactions.chain_id**
      *
      * Chain ID where transaction occurred (stored as text for large chain IDs)
      * - `text` in database
      * - `NOT NULL`, no default
      */
      chain_id?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
      /**
      * **transactions.created_at**
      * - `timestamptz` in database
      * - `NOT NULL`, default: `now()`
      */
      created_at?: (db.TimestampTzString | Date) | db.Parameter<(db.TimestampTzString | Date)> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, (db.TimestampTzString | Date) | db.Parameter<(db.TimestampTzString | Date)> | db.SQLFragment | db.ParentColumn>;
      /**
      * **transactions.cumulative_gas_used**
      *
      * Total gas used by transaction (stored as text for precision)
      * - `text` in database
      * - `NOT NULL`, no default
      */
      cumulative_gas_used?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
      /**
      * **transactions.effective_gas_price**
      *
      * Effective gas price paid (stored as text for precision)
      * - `text` in database
      * - `NOT NULL`, no default
      */
      effective_gas_price?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
      /**
      * **transactions.from**
      *
      * Transaction sender address
      * - `text` in database
      * - `NOT NULL`, no default
      */
      from?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
      /**
      * **transactions.id**
      * - `uuid` in database
      * - `NOT NULL`, default: `uuid_generate_v4()`
      */
      id?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
      /**
      * **transactions.metadata**
      *
      * Additional transaction-specific data stored as JSON
      * - `jsonb` in database
      * - Nullable, default: `'{}'::jsonb`
      */
      metadata?: db.JSONValue | db.Parameter<db.JSONValue> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, db.JSONValue | db.Parameter<db.JSONValue> | db.SQLFragment | db.ParentColumn>;
      /**
      * **transactions.reason**
      *
      * Transaction purpose/category (e.g., deposit, withdrawal, bridge, etc.)
      * - `text` in database
      * - `NOT NULL`, no default
      */
      reason?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
      /**
      * **transactions.rebalance_operation_id**
      *
      * Optional reference to associated rebalance operation (NULL for standalone transactions)
      * - `uuid` in database
      * - Nullable, no default
      */
      rebalance_operation_id?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
      /**
      * **transactions.to**
      *
      * Transaction destination address
      * - `text` in database
      * - `NOT NULL`, no default
      */
      to?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
      /**
      * **transactions.transaction_hash**
      *
      * On-chain transaction hash
      * - `text` in database
      * - `NOT NULL`, no default
      */
      transaction_hash?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
      /**
      * **transactions.updated_at**
      * - `timestamptz` in database
      * - `NOT NULL`, default: `now()`
      */
      updated_at?: (db.TimestampTzString | Date) | db.Parameter<(db.TimestampTzString | Date)> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, (db.TimestampTzString | Date) | db.Parameter<(db.TimestampTzString | Date)> | db.SQLFragment | db.ParentColumn>;
    }
    export interface Insertable {
      /**
      * **transactions.chain_id**
      *
      * Chain ID where transaction occurred (stored as text for large chain IDs)
      * - `text` in database
      * - `NOT NULL`, no default
      */
      chain_id: string | db.Parameter<string> | db.SQLFragment;
      /**
      * **transactions.created_at**
      * - `timestamptz` in database
      * - `NOT NULL`, default: `now()`
      */
      created_at?: (db.TimestampTzString | Date) | db.Parameter<(db.TimestampTzString | Date)> | db.DefaultType | db.SQLFragment;
      /**
      * **transactions.cumulative_gas_used**
      *
      * Total gas used by transaction (stored as text for precision)
      * - `text` in database
      * - `NOT NULL`, no default
      */
      cumulative_gas_used: string | db.Parameter<string> | db.SQLFragment;
      /**
      * **transactions.effective_gas_price**
      *
      * Effective gas price paid (stored as text for precision)
      * - `text` in database
      * - `NOT NULL`, no default
      */
      effective_gas_price: string | db.Parameter<string> | db.SQLFragment;
      /**
      * **transactions.from**
      *
      * Transaction sender address
      * - `text` in database
      * - `NOT NULL`, no default
      */
      from: string | db.Parameter<string> | db.SQLFragment;
      /**
      * **transactions.id**
      * - `uuid` in database
      * - `NOT NULL`, default: `uuid_generate_v4()`
      */
      id?: string | db.Parameter<string> | db.DefaultType | db.SQLFragment;
      /**
      * **transactions.metadata**
      *
      * Additional transaction-specific data stored as JSON
      * - `jsonb` in database
      * - Nullable, default: `'{}'::jsonb`
      */
      metadata?: db.JSONValue | db.Parameter<db.JSONValue> | null | db.DefaultType | db.SQLFragment;
      /**
      * **transactions.reason**
      *
      * Transaction purpose/category (e.g., deposit, withdrawal, bridge, etc.)
      * - `text` in database
      * - `NOT NULL`, no default
      */
      reason: string | db.Parameter<string> | db.SQLFragment;
      /**
      * **transactions.rebalance_operation_id**
      *
      * Optional reference to associated rebalance operation (NULL for standalone transactions)
      * - `uuid` in database
      * - Nullable, no default
      */
      rebalance_operation_id?: string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment;
      /**
      * **transactions.to**
      *
      * Transaction destination address
      * - `text` in database
      * - `NOT NULL`, no default
      */
      to: string | db.Parameter<string> | db.SQLFragment;
      /**
      * **transactions.transaction_hash**
      *
      * On-chain transaction hash
      * - `text` in database
      * - `NOT NULL`, no default
      */
      transaction_hash: string | db.Parameter<string> | db.SQLFragment;
      /**
      * **transactions.updated_at**
      * - `timestamptz` in database
      * - `NOT NULL`, default: `now()`
      */
      updated_at?: (db.TimestampTzString | Date) | db.Parameter<(db.TimestampTzString | Date)> | db.DefaultType | db.SQLFragment;
    }
    export interface Updatable {
      /**
      * **transactions.chain_id**
      *
      * Chain ID where transaction occurred (stored as text for large chain IDs)
      * - `text` in database
      * - `NOT NULL`, no default
      */
      chain_id?: string | db.Parameter<string> | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment>;
      /**
      * **transactions.created_at**
      * - `timestamptz` in database
      * - `NOT NULL`, default: `now()`
      */
      created_at?: (db.TimestampTzString | Date) | db.Parameter<(db.TimestampTzString | Date)> | db.DefaultType | db.SQLFragment | db.SQLFragment<any, (db.TimestampTzString | Date) | db.Parameter<(db.TimestampTzString | Date)> | db.DefaultType | db.SQLFragment>;
      /**
      * **transactions.cumulative_gas_used**
      *
      * Total gas used by transaction (stored as text for precision)
      * - `text` in database
      * - `NOT NULL`, no default
      */
      cumulative_gas_used?: string | db.Parameter<string> | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment>;
      /**
      * **transactions.effective_gas_price**
      *
      * Effective gas price paid (stored as text for precision)
      * - `text` in database
      * - `NOT NULL`, no default
      */
      effective_gas_price?: string | db.Parameter<string> | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment>;
      /**
      * **transactions.from**
      *
      * Transaction sender address
      * - `text` in database
      * - `NOT NULL`, no default
      */
      from?: string | db.Parameter<string> | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment>;
      /**
      * **transactions.id**
      * - `uuid` in database
      * - `NOT NULL`, default: `uuid_generate_v4()`
      */
      id?: string | db.Parameter<string> | db.DefaultType | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | db.DefaultType | db.SQLFragment>;
      /**
      * **transactions.metadata**
      *
      * Additional transaction-specific data stored as JSON
      * - `jsonb` in database
      * - Nullable, default: `'{}'::jsonb`
      */
      metadata?: db.JSONValue | db.Parameter<db.JSONValue> | null | db.DefaultType | db.SQLFragment | db.SQLFragment<any, db.JSONValue | db.Parameter<db.JSONValue> | null | db.DefaultType | db.SQLFragment>;
      /**
      * **transactions.reason**
      *
      * Transaction purpose/category (e.g., deposit, withdrawal, bridge, etc.)
      * - `text` in database
      * - `NOT NULL`, no default
      */
      reason?: string | db.Parameter<string> | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment>;
      /**
      * **transactions.rebalance_operation_id**
      *
      * Optional reference to associated rebalance operation (NULL for standalone transactions)
      * - `uuid` in database
      * - Nullable, no default
      */
      rebalance_operation_id?: string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment>;
      /**
      * **transactions.to**
      *
      * Transaction destination address
      * - `text` in database
      * - `NOT NULL`, no default
      */
      to?: string | db.Parameter<string> | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment>;
      /**
      * **transactions.transaction_hash**
      *
      * On-chain transaction hash
      * - `text` in database
      * - `NOT NULL`, no default
      */
      transaction_hash?: string | db.Parameter<string> | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment>;
      /**
      * **transactions.updated_at**
      * - `timestamptz` in database
      * - `NOT NULL`, default: `now()`
      */
      updated_at?: (db.TimestampTzString | Date) | db.Parameter<(db.TimestampTzString | Date)> | db.DefaultType | db.SQLFragment | db.SQLFragment<any, (db.TimestampTzString | Date) | db.Parameter<(db.TimestampTzString | Date)> | db.DefaultType | db.SQLFragment>;
    }
    export type UniqueIndex = 'transactions_pkey' | 'unique_tx_chain';
    export type Column = keyof Selectable;
    export type OnlyCols<T extends readonly Column[]> = Pick<Selectable, T[number]>;
    export type SQLExpression = Table | db.ColumnNames<Updatable | (keyof Updatable)[]> | db.ColumnValues<Updatable> | Whereable | Column | db.ParentColumn | db.GenericSQLExpression;
    export type SQL = SQLExpression | SQLExpression[];
  }

  /* --- aggregate types --- */

  export namespace public {  
    export type Table = admin_actions.Table | cex_withdrawals.Table | earmarks.Table | rebalance_operations.Table | schema_migrations.Table | transactions.Table;
    export type Selectable = admin_actions.Selectable | cex_withdrawals.Selectable | earmarks.Selectable | rebalance_operations.Selectable | schema_migrations.Selectable | transactions.Selectable;
    export type JSONSelectable = admin_actions.JSONSelectable | cex_withdrawals.JSONSelectable | earmarks.JSONSelectable | rebalance_operations.JSONSelectable | schema_migrations.JSONSelectable | transactions.JSONSelectable;
    export type Whereable = admin_actions.Whereable | cex_withdrawals.Whereable | earmarks.Whereable | rebalance_operations.Whereable | schema_migrations.Whereable | transactions.Whereable;
    export type Insertable = admin_actions.Insertable | cex_withdrawals.Insertable | earmarks.Insertable | rebalance_operations.Insertable | schema_migrations.Insertable | transactions.Insertable;
    export type Updatable = admin_actions.Updatable | cex_withdrawals.Updatable | earmarks.Updatable | rebalance_operations.Updatable | schema_migrations.Updatable | transactions.Updatable;
    export type UniqueIndex = admin_actions.UniqueIndex | cex_withdrawals.UniqueIndex | earmarks.UniqueIndex | rebalance_operations.UniqueIndex | schema_migrations.UniqueIndex | transactions.UniqueIndex;
    export type Column = admin_actions.Column | cex_withdrawals.Column | earmarks.Column | rebalance_operations.Column | schema_migrations.Column | transactions.Column;
  
    export type AllBaseTables = [admin_actions.Table, cex_withdrawals.Table, earmarks.Table, rebalance_operations.Table, schema_migrations.Table, transactions.Table];
    export type AllForeignTables = [];
    export type AllViews = [];
    export type AllMaterializedViews = [];
    export type AllTablesAndViews = [admin_actions.Table, cex_withdrawals.Table, earmarks.Table, rebalance_operations.Table, schema_migrations.Table, transactions.Table];
  }



  /* === global aggregate types === */

  export type Schema = 'public';
  export type Table = public.Table;
  export type Selectable = public.Selectable;
  export type JSONSelectable = public.JSONSelectable;
  export type Whereable = public.Whereable;
  export type Insertable = public.Insertable;
  export type Updatable = public.Updatable;
  export type UniqueIndex = public.UniqueIndex;
  export type Column = public.Column;

  export type AllSchemas = ['public'];
  export type AllBaseTables = [...public.AllBaseTables];
  export type AllForeignTables = [...public.AllForeignTables];
  export type AllViews = [...public.AllViews];
  export type AllMaterializedViews = [...public.AllMaterializedViews];
  export type AllTablesAndViews = [...public.AllTablesAndViews];


  /* === lookups === */

  export type SelectableForTable<T extends Table> = {
    "admin_actions": admin_actions.Selectable;
    "cex_withdrawals": cex_withdrawals.Selectable;
    "earmarks": earmarks.Selectable;
    "rebalance_operations": rebalance_operations.Selectable;
    "schema_migrations": schema_migrations.Selectable;
    "transactions": transactions.Selectable;
  }[T];

  export type JSONSelectableForTable<T extends Table> = {
    "admin_actions": admin_actions.JSONSelectable;
    "cex_withdrawals": cex_withdrawals.JSONSelectable;
    "earmarks": earmarks.JSONSelectable;
    "rebalance_operations": rebalance_operations.JSONSelectable;
    "schema_migrations": schema_migrations.JSONSelectable;
    "transactions": transactions.JSONSelectable;
  }[T];

  export type WhereableForTable<T extends Table> = {
    "admin_actions": admin_actions.Whereable;
    "cex_withdrawals": cex_withdrawals.Whereable;
    "earmarks": earmarks.Whereable;
    "rebalance_operations": rebalance_operations.Whereable;
    "schema_migrations": schema_migrations.Whereable;
    "transactions": transactions.Whereable;
  }[T];

  export type InsertableForTable<T extends Table> = {
    "admin_actions": admin_actions.Insertable;
    "cex_withdrawals": cex_withdrawals.Insertable;
    "earmarks": earmarks.Insertable;
    "rebalance_operations": rebalance_operations.Insertable;
    "schema_migrations": schema_migrations.Insertable;
    "transactions": transactions.Insertable;
  }[T];

  export type UpdatableForTable<T extends Table> = {
    "admin_actions": admin_actions.Updatable;
    "cex_withdrawals": cex_withdrawals.Updatable;
    "earmarks": earmarks.Updatable;
    "rebalance_operations": rebalance_operations.Updatable;
    "schema_migrations": schema_migrations.Updatable;
    "transactions": transactions.Updatable;
  }[T];

  export type UniqueIndexForTable<T extends Table> = {
    "admin_actions": admin_actions.UniqueIndex;
    "cex_withdrawals": cex_withdrawals.UniqueIndex;
    "earmarks": earmarks.UniqueIndex;
    "rebalance_operations": rebalance_operations.UniqueIndex;
    "schema_migrations": schema_migrations.UniqueIndex;
    "transactions": transactions.UniqueIndex;
  }[T];

  export type ColumnForTable<T extends Table> = {
    "admin_actions": admin_actions.Column;
    "cex_withdrawals": cex_withdrawals.Column;
    "earmarks": earmarks.Column;
    "rebalance_operations": rebalance_operations.Column;
    "schema_migrations": schema_migrations.Column;
    "transactions": transactions.Column;
  }[T];

  export type SQLForTable<T extends Table> = {
    "admin_actions": admin_actions.SQL;
    "cex_withdrawals": cex_withdrawals.SQL;
    "earmarks": earmarks.SQL;
    "rebalance_operations": rebalance_operations.SQL;
    "schema_migrations": schema_migrations.SQL;
    "transactions": transactions.SQL;
  }[T];

}
