global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'mark-poller'
    honor_labels: true
    metrics_path: /metrics
    static_configs:
      - targets: ['pushgateway:9091']
