name: Test Release
on:
  pull_request:

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

defaults:
  run:
    working-directory: packages/contracts

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: 'yarn'

      - name: Check Yarn version
        run: yarn --version

      - name: Install dependencies
        run: yarn install

      - name: Build repository
        run: yarn build

      - name: Run tests
        shell: bash
        run: yarn test:unit

      - name: Yarn lint
        env:
          NODE_OPTIONS: '--max-old-space-size=12288'
        run: yarn lint:check
